### ISSUE TITLE
Doesn't load on 1.8.9

### ISSUE THREAD

**Issue by GirafiStudios** [bonii-xx/TestDummy#5]
So LexManos fix for getting 1.8.8 didn't work in all cases, the acceptedMinecraftVersions have to be only [1.8.8] for it work on 1.8.9 and since you're using acceptedMinecraftVersions="[1.8,1.8.8]", it doesn't wanna load.. x)

Screenshot as proof I guess.. : https://gyazo.com/599624738474b9f1d0bf8e04442dc285

**Comment by bonii-xx** [comment]
Fixed.
